<?xml version="1.0"?>
<package format="3">
  <name>zcw_px4_baseline</name>
  <version>0.0.1</version>
  <description>PX4 ROS 2 baseline control nodes adapted from official PX4 examples.</description>
  <maintainer email="todo@example.com">zcw</maintainer>
  <license>BSD-3-Clause</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>px4_msgs</depend>
  <depend>rclcpp</depend>
  <depend>geometry_msgs</depend>
  <depend>std_msgs</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
